var dir_2d0ecdf63b465107bcb380717c9ee971 =
[
    [ "adc.h", "adc_8h.html", "adc_8h" ],
    [ "batt.h", "batt_8h.html", "batt_8h" ],
    [ "Board1.h", "_board1_8h_source.html", null ],
    [ "board1_functions.h", "board1__functions_8h_source.html", null ],
    [ "Board1_private.h", "_board1__private_8h_source.html", null ],
    [ "Board1_types.h", "_board1__types_8h_source.html", null ],
    [ "crc.h", "_board1_2board1__firmware_2_core_2_inc_2crc_8h.html", null ],
    [ "deadline_watchdog.h", "_board1_2board1__firmware_2_core_2_inc_2deadline__watchdog_8h.html", "_board1_2board1__firmware_2_core_2_inc_2deadline__watchdog_8h" ],
    [ "dma.h", "_board1_2board1__firmware_2_core_2_inc_2dma_8h.html", "_board1_2board1__firmware_2_core_2_inc_2dma_8h" ],
    [ "encoder.h", "encoder_8h.html", "encoder_8h" ],
    [ "FreeRTOSConfig.h", "_board1_2board1__firmware_2_core_2_inc_2_free_r_t_o_s_config_8h_source.html", null ],
    [ "gpio.h", "_board1_2board1__firmware_2_core_2_inc_2gpio_8h.html", "_board1_2board1__firmware_2_core_2_inc_2gpio_8h" ],
    [ "hw_calibration.h", "_board1_2board1__firmware_2_core_2_inc_2hw__calibration_8h.html", "_board1_2board1__firmware_2_core_2_inc_2hw__calibration_8h" ],
    [ "hw_config.h", "_board1_2board1__firmware_2_core_2_inc_2hw__config_8h.html", "_board1_2board1__firmware_2_core_2_inc_2hw__config_8h" ],
    [ "led.h", "led_8h.html", "led_8h" ],
    [ "led_stripes.h", "led__stripes_8h.html", "led__stripes_8h" ],
    [ "main.h", "_board1_2board1__firmware_2_core_2_inc_2main_8h.html", "_board1_2board1__firmware_2_core_2_inc_2main_8h" ],
    [ "motor.h", "_board1_2board1__firmware_2_core_2_inc_2motor_8h.html", "_board1_2board1__firmware_2_core_2_inc_2motor_8h" ],
    [ "motor_diagnostic.h", "motor__diagnostic_8h.html", "motor__diagnostic_8h" ],
    [ "pid_law.h", "pid__law_8h.html", "pid__law_8h" ],
    [ "rtwtypes.h", "_board1_2board1__firmware_2_core_2_inc_2rtwtypes_8h_source.html", null ],
    [ "stm32g4xx_hal_conf.h", "_board1_2board1__firmware_2_core_2_inc_2stm32g4xx__hal__conf_8h.html", "_board1_2board1__firmware_2_core_2_inc_2stm32g4xx__hal__conf_8h" ],
    [ "stm32g4xx_it.h", "_board1_2board1__firmware_2_core_2_inc_2stm32g4xx__it_8h.html", "_board1_2board1__firmware_2_core_2_inc_2stm32g4xx__it_8h" ],
    [ "temp.h", "temp_8h.html", "temp_8h" ],
    [ "tim.h", "_board1_2board1__firmware_2_core_2_inc_2tim_8h.html", "_board1_2board1__firmware_2_core_2_inc_2tim_8h" ],
    [ "usart.h", "_board1_2board1__firmware_2_core_2_inc_2usart_8h.html", null ],
    [ "utils.h", "_board1_2board1__firmware_2_core_2_inc_2utils_8h_source.html", null ]
];